### ISSUE TITLE
New QT6 Update Broke PrimeHack

### ISSUE THREAD

**Issue by GatorMilkMerchant** [shiiion/dolphin#160] opened 2024-03-05 03:52 UTC
After the new QT6 update, many Flatpaks had the following error when launched:
"dolphin-emu: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6"

This was also on Citra, Dolphin, and 2 other flatpaks. I saw those be resolved already.
![primehack error](https://github.com/shiiion/dolphin/assets/162073386/f5f20bb4-745d-442e-8da6-3c223ccbfd70)

**Comment by SirMangler** [comment] 2024-03-05 11:06
This is a duplicate of: https://github.com/flathub/io.github.shiiion.primehack/issues/30

**Closed as completed by SirMangler** 2024-03-05 11:06 UTC
